version: '3.8'
services:
    postgres:
        image: postgres:latest
        container_name: my-postgres
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydb
        ports:
            - '5432:5432'
        volumes:
            - my-postgres-data:/var/lib/postgresql/data

volumes:
    my-postgres-data:
